### ISSUE TITLE
Export onnx model

### ISSUE THREAD

**Issue by cvbuff** [nanmi/yolov7-pose#1]
请问pt转onnx是需要修改forward么，但是转模型时候我没有看到有调用yolo.py ，所以不知道是修改哪里的forward，还是需要修改forward后重新训练呢

**Comment by zzz3bbb3** [comment]
Yes, the forward needs to be modified, because in order to remove the reshap operation and dimension transformation, it needs to be shielded, and the big lump behind the forward becomes a concise tensorrt plugin

**Comment by zzz3bbb3** [comment]
You should modify is the forward function in the keypoint-related code `class IKeypoint(nn.Module)`
