### ISSUE TITLE
make: *** No targets specified and no makefile found.  Stop.

### ISSUE THREAD

**Issue by fandy0123456** [nanmi/yolov7-pose#16]
cd YoloLayer_TRT_v7.0
mkdir build && cd build
cmake .. && make

and Tip     

-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19045.
-- The C compiler identification is MSVC 19.29.30147.0
-- The CXX compiler identification is MSVC 19.29.30147.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: d:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: d:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.0 (found version "12.0") 
-- Configuring done
-- Generating done
-- Build files have been written to: E:/VSCodeSource/yolo2onnx/YoloLayer_TRT_v7.0/build
make: *** No targets specified and no makefile found.  Stop.

can't 'get yolo.so' file

**Comment by nanmi** [comment]
It is possible that Yolo. lib was generated in the Win system, and this project has only been tested in the Ubuntu system. Please check it out
