### ISSUE TITLE
严重性	代码	说明	项目	文件	行	禁止显示状态 错误	LNK1181	无法打开输入文件“D:\workshop\deeplearning\yolov7-pose-main\build\CMakeFiles\yolov7_pose.dir\Release\yolov7_pose_generated_yololayer.cu.obj”	yolov7_pose	D:\workshop\deeplearning\yolov7-pose-main\build\LINK	1	

### ISSUE THREAD

**Issue by ChristoCai** [nanmi/yolov7-pose#17]
environment：
window 10
CUDA 11.8
TensorRT 8.x
VS 2019

The following error occurred when I compiled the project. I don't know if it is the reason for cmake。
![image](https://user-images.githubusercontent.com/54760160/217988388-7c9e1320-b8a9-46ee-901d-a90e2db735f3.png)

**Comment by zzz3bbb3** [comment]
The project has only been tested and passed in the Linux system

**Comment by shuibeiyy** [comment]
直接移除yolov7_pose_generated_yololayer.cu.[obj文件]
