### ISSUE TITLE
57001是怎么来的

### ISSUE THREAD

**Issue by lifeng0718** [nanmi/yolov7-pose#19]

**Comment by zzz3bbb3** [comment]
yes, max output num is 1000, and each keypoint has three numbers(x, y, kpt_conf) [L30](https://github.com/nanmi/yolov7-pose/blob/bd8f06fc16b3d0df829e5ee4a23cb8cec59f1a29/YoloLayer_TRT_v7.0/yololayer.h#L30) and we have 17 keypoints, so 3(x, y, kpt_conf) * 17(keypoints num) + 4(bbox) + 1(score) + 1(label) = 57, and we will get max output = 57 * 1000(max output num) + 1

**Comment by YunghuiHsu** [comment]
Thank you Very clear instructions.
May I ask why need to "add 1"

**Comment by zzz3bbb3** [comment]
In order to adapt to the cuda code of the plugin, it is also possible to reduce the number of atoms in the cuda code of the plugin by adding one
