### ISSUE TITLE
The final inference is not accurate

### ISSUE THREAD

**Issue by DaoLewis614** [nanmi/yolov7-pose#27]
I have transferred yolov7-w6-pose.pt to  yolov7-w6-pose.onnx. 
And simply it into yolov7-w6-pose-sim.onnx. 
Using the code, output the yolov7-w6-sim-yolo.sim.
Finally, I generate the engine successfully.

## While the results is wrong 
![Screenshot from 2023-10-18 19-01-16](https://github.com/nanmi/yolov7-pose/assets/145033578/317e78aa-8ffb-4dda-8e08-886be5b39113)

### Need I retrain the model cuz I have changed the forward function of IKeypoint? Or need I re-parameterize the yolov7-w6-pose.pt?

**Comment by wuba-pat** [comment]
Have you resolved this problem?

I met the same situation.
![Uploading _result.jpg…]()
