### ISSUE TITLE
The target detection result is wrong

### ISSUE THREAD

**Issue by jiaerwang0328** [nanmi/yolov7-pose#3]
hi. Thanks for your work！
I followed the tutorial to convert the model, the inference is successful, but the detection result is wrong, did I do something wrong.
![_result](https://user-images.githubusercontent.com/38750407/189266310-4e51a9dc-9daa-4db7-a8d5-27d4dbfa2d07.jpg)

**Comment by zzz3bbb3** [comment]
It looks like the anchors are not set correctly or the normalization inverse process is not done.

**Comment by NTS-SW** [comment]
what should I do infer correctly?

**Comment by Byronnar** [comment]
> what should I do infer correctly?

Have you solved this problem? I also find this error.

**Comment by Byronnar** [comment]
> It looks like the anchors are not set correctly or the normalization inverse process is not done.
Could please tell us what should  do infer correctly? Thank you
