### ISSUE TITLE
Are there any code for inference with python

### ISSUE THREAD

**Issue by dinushazoomi** [nanmi/yolov7-pose#4]
Hi, thanks for the work on the tensorRT conversion of the yolov7-pose, I was able to successfully convert the PyTorch model to tensorRT engine. Is there any python script that can be used to infer it?

**Comment by dinushazoomi** [comment]
I have created a code for the inference using python.

**Comment by simon5u** [comment]
@dinushazoomi can you share the python inference code here? thanks!

**Comment by ggzzzzz628** [comment]
@dinushazoomi can you share the python inference code here? thanks!

**Comment by dinusha94** [comment]
@gzchenjiajun @simon5u code is available at https://github.com/dinusha94/yolo-pose

**Comment by ggzzzzz628** [comment]
@dinusha94 thks!
