### ISSUE TITLE
why outsize's dim is 57001?

### ISSUE THREAD

**Issue by YaoBeiji** [nanmi/yolov7-pose#8]
why outsize's dim is 57001?  my onnx dim is 57375.

**Comment by Gwencong** [comment]
It seems that 57001=maxoutput*57+1 in the [yolo layer plugin code](https://github.com/nanmi/yolov7-pose/blob/main/YoloLayer_TRT_v7.0/yololayer.cu#L116-L118), which means that the yololayer plugin just outputs 1000 person, the size of each person is 57

**Comment by zzz3bbb3** [comment]
yes, max output num is 1000, and each keypoint has three numbers(x, y, kpt_conf) [L30](https://github.com/nanmi/yolov7-pose/blob/bd8f06fc16b3d0df829e5ee4a23cb8cec59f1a29/YoloLayer_TRT_v7.0/yololayer.h#L30) and we have 17 keypoints, so 3(x, y, kpt_conf) * 17(keypoints num) + 4(bbox) + 1(score) + 1(label) = 57, and we will get max output = 57 * 1000(max output num) + 1
